# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudySwitUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for StudySwitUI

  target 'StudySwitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudySwitUIUITests' do
    # Pods for testing
  end

end
